# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('at_bat', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('homeruns', models.IntegerField()),
                ('rbi', models.IntegerField()),
            ],
        ),
    ]
