# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 18:50
from __future__ import unicode_literals

from django.db import migrations
import csv


def add_team_data(apps, schema_editor):
    Player = apps.get_model("my_app", "Player")
    with open('cubbies_data.csv') as infile:
        contents = csv.reader(infile)
        for row in contents:
            Player.objects.create(position=row[1], first_name=row[2], last_name=row[3], age=row[4], at_bat=row[5], runs=row[6], hits=row[7], homeruns=row[8], rbi=row[9])


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_team_data)
    ]
